In [110]:
#  追赶法
import numpy as np

def zg(A,b):
    n = len(A)
    e = []
    d = []
    f = []
    l = []
    for i in range(n-1):
        e.append(A[i][i])
        d.append(A[i+1][i])
        f.append(A[i][i+1])
    e.append(A[n-1][n-1])

    b = np.asarray(b, dtype=float).copy()

    for i in range(n-1):
        l.append(d[i]/(e[i]))
        e[i+1] = e[i+1] - l[i]*f[i]

    for i in range(1,n):
        b[i] = b[i] - l[i-1]*b[i-1]
    
    x = [0 for _ in range(n)]
    x[-1] = b[-1]/e[-1]
    for i in range(n-2,-1,-1):
        x[i] = (b[i]-f[i]*x[i+1])/e[i]

    return x



A = np.array([[2,1,0,0],[1,3,1,0],[0,1,1,1],[0,0,2,1]])
b = np.array([1,2,2,0])
x = zg(A,b)
print(x)

print(np.linalg.solve(A, [1.0,2,2,0])) 

[0.0, 1.0, -1.0000000000000002, 2.0]
[ 0.  1. -1.  2.]


In [111]:
# Jacobi and G-S
import numpy as np


def Jacobi(A,b,n,epsilon):
    l = len(A)
    x_ori = np.zeros(l)
    def diedai(x,A,b,l):
        x_new = np.copy(x)
        for i in range(l):
            sum0 = 0
            for j in range(l):
                if j != i:
                    sum0 = sum0 + A[i][j]*x[j]
            x_new[i] = (b[i] - sum0)/A[i][i]
        return x_new
    
    i = 0
    error = float('inf')
    while i < n and error>= epsilon:
        x = diedai(x_ori, A, b, l)
        error = np.linalg.norm(x - x_ori, 2)
        x_ori = x
        i += 1

    return x_ori


def G_S(A,b,n,epsilon):
    l = len(A)
    x_ori = np.zeros(l)
    def diedai(x,A,b,l):
        for i in range(l):
            sum0 = 0
            for j in range(l):
                if j != i:
                    sum0 = sum0 + A[i][j]*x[j]
            x[i] = (b[i] - sum0)/A[i][i]
        return x
    
    i = 0
    error = float('inf')
    while i < n and error>= epsilon:
        x_prev = x_ori.copy()
        x = diedai(x_prev, A, b, l)
        error = np.linalg.norm(x - x_prev, 2)
        x_ori = x
        i += 1
    
    return x_ori


A = np.array([[1,2,-2],[1,1,1],[2,2,1]])
b = np.array([1,1,1])

x_j = Jacobi(A,b,10000,0.00001)
x_G = G_S(A,b,10000,0.00001)



print(x_j)
print(x_G) 

[-3.  3.  1.]
[ 1.  0. -1.]


In [112]:
# Jacobi and G-S
import numpy as np


def Jacobi(A,b,n,epsilon):
    l = len(A)
    x_ori = np.zeros(l)
    def diedai(x,A,b,l):
        x_new = np.copy(x)
        for i in range(l):
            sum0 = 0
            for j in range(l):
                if j != i:
                    sum0 = sum0 + A[i][j]*x[j]
            x_new[i] = (b[i] - sum0)/A[i][i]
        return x_new
    
    i = 0
    error = float('inf')
    while i < n and error>= epsilon:
        x = diedai(x_ori, A, b, l)
        error = np.linalg.norm(b - A @ x, 2)
        x_ori = x
        i += 1

    print(error)
    print(i)

    return x_ori


def G_S(A,b,n,epsilon):
    l = len(A)
    x_ori = np.zeros(l)
    def diedai(x,A,b,l):
        for i in range(l):
            sum0 = 0
            for j in range(l):
                if j != i:
                    sum0 = sum0 + A[i][j]*x[j]
            x[i] = (b[i] - sum0)/A[i][i]
        return x
    
    i = 0
    error = float('inf')
    while i < n and error>= epsilon:
        x_prev = x_ori.copy()
        x = diedai(x_prev, A, b, l)
        error = np.linalg.norm(b - A @ x, 2)
        x_ori = x
        i += 1
    
    
    print(error)
    print(i)
    
    return x_ori


A = np.array([[1,2,-2],[1,1,1],[2,2,1]])
b = np.array([1,1,1])

x_j = Jacobi(A,b,10000,0.00001)
x_G = G_S(A,b,10000,0.00001)



print(x_j)
print(x_G) 

0.0
3
nan
1013
[-3.  3.  1.]
[-1.33071425e+308  1.33115314e+308              nan]


C:\Users\86182\AppData\Local\Temp\ipykernel_11908\1668596872.py:40: RuntimeWarning: overflow encountered in double_scalars
  sum0 = sum0 + A[i][j]*x[j]
C:\Users\86182\AppData\Local\Temp\ipykernel_11908\1668596872.py:40: RuntimeWarning: invalid value encountered in double_scalars
  sum0 = sum0 + A[i][j]*x[j]
C:\Users\86182\AppData\Local\Temp\ipykernel_11908\1668596872.py:49: RuntimeWarning: overflow encountered in matmul
  error = np.linalg.norm(b - A @ x, 2)
